"""
Generates a camera-relative spatial graph of reference views: 18 neutrally-named
nodes (view_000 .. view_017), connected by edges that each correspond to exactly
one elementary VTK camera action actually applied at render time.

This replaces the semantic-label approach in reference_views.py (which reset to
one absolute "Dorsal" camera and applied independently-computed (azimuth,
elevation) pairs for every view) with a graph-native approach:

  - No node is generated from an absolute (azimuth, elevation) pair.
  - Every non-root node has exactly one parent and is generated by:
      1. restoring the parent's exact saved camera state (get_camera_state /
         set_camera_state, from camera_state.py),
      2. applying exactly ONE elementary action (camera.Azimuth(d) or
         camera.Elevation(d)),
      3. camera.OrthogonalizeViewUp(),
      4. renderer.ResetCameraClippingRange(),
      5. rendering + saving the screenshot,
      6. saving the resulting camera state.

This is required because 3D rotations do not commute: subtracting two
independently-generated absolute azimuth/elevation values would NOT reproduce
the camera action that actually needs to be applied to move between two views.
Every edge in the resulting graph corresponds to a real, replayable VTK call.

Node IDs are intentionally neutral (view_000, view_001, ...) — no anatomical or
directional labels (Dorsal/Plantar/Medial/Lateral/Distal/Proximal) appear
anywhere in this module. camera_spatial_graph.py consumes camera_nodes.json to
build the full node+edge graph (auto-deriving inverse edges).
"""
import json
from pathlib import Path
from typing import Dict, List, Optional

from .camera_state import get_camera_state, set_camera_state
from .volume_scene import build_isosurface_pipeline, load_raw_volume, save_screenshot

# ======================================================================
# CALIBRATION — the root camera state. Every other node descends from this
# by a chain of single elementary actions (see VIEW_GENERATION_PLAN below).
# Replace with your manually-calibrated camera once you have it.
# ======================================================================
INITIAL_CAMERA = {
    "position": (-624.664, 118.625, 121.945),
    "focal_point": (142.426, 118.625, 121.945),
    "view_up": (0.0, 1.0, 0.0),
    "parallel_projection": False,
    "parallel_scale": None,
}

# ======================================================================
# VIEW_GENERATION_PLAN — 18 nodes, one entry per node, in an order where each
# node's parent_id always appears earlier in the list. The root (view_000) has
# parent_id=None and action=None. Every other node has exactly one parent and
# exactly one elementary action ({"type": "azimuth"|"elevation", "degrees": f}).
#
# Both positive and negative azimuth and elevation are represented. Some nodes
# are direct children of the root (broad primary coverage); others are one
# more elementary step away from a level-1 node (oblique coverage), so the
# resulting camera pose is the actual composition of the chain of single ops
# applied along the path from the root — never an independently-computed
# absolute pair.
# ======================================================================
VIEW_GENERATION_PLAN: List[dict] = [
    {"node_id": "view_000", "parent_id": None, "action": None},

    # Level 1 — direct children of the root.
    {"node_id": "view_001", "parent_id": "view_000", "action": {"type": "azimuth", "degrees": 45.0}},
    {"node_id": "view_002", "parent_id": "view_000", "action": {"type": "azimuth", "degrees": -45.0}},
    {"node_id": "view_003", "parent_id": "view_000", "action": {"type": "azimuth", "degrees": 90.0}},
    {"node_id": "view_004", "parent_id": "view_000", "action": {"type": "azimuth", "degrees": -90.0}},
    {"node_id": "view_005", "parent_id": "view_000", "action": {"type": "elevation", "degrees": 45.0}},
    {"node_id": "view_006", "parent_id": "view_000", "action": {"type": "elevation", "degrees": -45.0}},
    {"node_id": "view_007", "parent_id": "view_000", "action": {"type": "elevation", "degrees": 90.0}},
    {"node_id": "view_008", "parent_id": "view_000", "action": {"type": "elevation", "degrees": -90.0}},

    # Level 2 — one further elementary step from a level-1 node (oblique coverage).
    {"node_id": "view_009", "parent_id": "view_001", "action": {"type": "elevation", "degrees": 45.0}},
    {"node_id": "view_010", "parent_id": "view_001", "action": {"type": "elevation", "degrees": -45.0}},
    {"node_id": "view_011", "parent_id": "view_002", "action": {"type": "elevation", "degrees": 45.0}},
    {"node_id": "view_012", "parent_id": "view_002", "action": {"type": "elevation", "degrees": -45.0}},
    {"node_id": "view_013", "parent_id": "view_003", "action": {"type": "elevation", "degrees": 45.0}},
    {"node_id": "view_014", "parent_id": "view_003", "action": {"type": "elevation", "degrees": -45.0}},
    {"node_id": "view_015", "parent_id": "view_004", "action": {"type": "elevation", "degrees": 45.0}},
    {"node_id": "view_016", "parent_id": "view_004", "action": {"type": "elevation", "degrees": -45.0}},
    {"node_id": "view_017", "parent_id": "view_005", "action": {"type": "azimuth", "degrees": 45.0}},
]

assert len(VIEW_GENERATION_PLAN) == 18
assert len({n["node_id"] for n in VIEW_GENERATION_PLAN}) == 18


def _apply_root_camera(camera) -> None:
    camera.SetPosition(*INITIAL_CAMERA["position"])
    camera.SetFocalPoint(*INITIAL_CAMERA["focal_point"])
    camera.SetViewUp(*INITIAL_CAMERA["view_up"])
    camera.SetParallelProjection(INITIAL_CAMERA["parallel_projection"])
    if INITIAL_CAMERA["parallel_projection"] and INITIAL_CAMERA["parallel_scale"]:
        camera.SetParallelScale(INITIAL_CAMERA["parallel_scale"])


def _full_camera_metadata(camera) -> dict:
    """Full camera state, matching the schema camera_spatial_graph.py expects
    for each node's "camera" field."""
    parallel = bool(camera.GetParallelProjection())
    return {
        "position": list(camera.GetPosition()),
        "focal_point": list(camera.GetFocalPoint()),
        "view_up": list(camera.GetViewUp()),
        "direction_of_projection": list(camera.GetDirectionOfProjection()),
        "clipping_range": list(camera.GetClippingRange()),
        "parallel_projection": parallel,
        "parallel_scale": camera.GetParallelScale() if parallel else None,
        "view_angle": camera.GetViewAngle(),
        "distance": camera.GetDistance(),
        "roll": camera.GetRoll(),
    }


def generate_camera_relative_views(
    raw_path: str,
    dimensions: tuple,
    scalar_type: str = "uint8",
    isovalue: float = 80,
    output_dir: str = "reference_views_relative",
    plan: Optional[List[dict]] = None,
) -> List[dict]:
    """Render and save all 18 camera-relative graph nodes + their metadata.

    Output layout:
      {output_dir}/view_000.png .. view_017.png
      {output_dir}/camera_nodes.json   (flat per-node records: node_id, parent_id,
                                         action, image_path, camera)

    Returns the list of per-node metadata dicts (same content written to
    camera_nodes.json). Use CameraSpatialGraph.from_camera_nodes(...) to turn
    this flat list into a full node+edge graph (with auto-derived inverses).
    """
    plan = plan if plan is not None else VIEW_GENERATION_PLAN

    image_data = load_raw_volume(raw_path, dimensions, scalar_type)
    _actor, renderer, render_window = build_isosurface_pipeline(image_data, isovalue)
    camera = renderer.GetActiveCamera()

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # node_id -> get_camera_state()-style state (position/focal_point/view_up/
    # view_angle/clipping_range), used to restore a parent's *exact* state
    # before applying its child's single action.
    saved_states: Dict[str, dict] = {}
    records: List[dict] = []

    for entry in plan:
        node_id = entry["node_id"]
        parent_id = entry["parent_id"]
        action = entry["action"]

        if parent_id is None:
            _apply_root_camera(camera)
        else:
            if parent_id not in saved_states:
                raise ValueError(
                    f"Node {node_id!r} references parent {parent_id!r}, which has not "
                    "been generated yet. VIEW_GENERATION_PLAN must list every node's "
                    "parent before the node itself."
                )
            set_camera_state(camera, saved_states[parent_id])
            if action["type"] == "azimuth":
                camera.Azimuth(action["degrees"])
            elif action["type"] == "elevation":
                camera.Elevation(action["degrees"])
            else:
                raise ValueError(f"Unsupported action type: {action['type']!r}")

        camera.OrthogonalizeViewUp()
        renderer.ResetCameraClippingRange()

        image_path = out_dir / f"{node_id}.png"
        save_screenshot(render_window, str(image_path))

        saved_states[node_id] = get_camera_state(camera)

        record = {
            "node_id": node_id,
            "parent_id": parent_id,
            "action": action,
            "image_path": str(image_path),
            "camera": _full_camera_metadata(camera),
        }
        records.append(record)
        print(f"[camera_relative_views] Saved {node_id} (parent={parent_id}, action={action}) -> {image_path}")

    nodes_path = out_dir / "camera_nodes.json"
    with open(nodes_path, "w") as f:
        json.dump(records, f, indent=2)
    print(f"[camera_relative_views] Wrote {len(records)} node records to {nodes_path}")

    return records
